import './globals.scss';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { ReactNode } from 'react';
import { getUserBySessionToken } from '../database/users';
import { reactStrictMode } from '../next.config';
import LoginForm from './(auth)/login/LoginForm';
import RegisterForm from './(auth)/register/RegisterForm';
import { LogoutButton } from './LogoutButton';

const inter = Inter({ subsets: ['latin'] });
type Props = {
  children: ReactNode;
};
export const metadata = {
  title: { default: 'Main Page', template: '%s | Gaming Galaxy  ' },
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Props) {
  // 1. get the session token from the cookie
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user = !sessionToken?.value
    ? undefined
    : await getUserBySessionToken(sessionToken.value);

  /*   return (
    <><html lang="en" className="bg-[#ACC8E5] text-[#142C47] box-border">
      <nav>
        <div className="flex justify-evenly my-8">
          <div className="site-logo">
            <Link href="/">LOGO Gaming forum LOGO</Link>
          </div>
          <div className="user-signin">
            <div>GameByte Community</div>
            <div>
              <LoginForm>Log In</LoginForm>
            </div>
            <div>
              <Link href="/register">Sign Up here!</Link>
            </div>
            <a>Profile</a>
          </div>
        </div>
      </>
      <body className={inter.className}>{children}</body>
    </nav><footer>
        <div className="flex justify-evenly my-20">
          <span>About Us</span>
          <span>Contacts</span>
        </div>
      </footer></>
    </html>
  ); */
  return (
    <html lang="en" className="bg-[#ACC8E5] text-[#142C47] box-border">
      <body>
        <nav className="flex justify-evenly items my-8 p-8">
          <div>
            <Link href="/">LOGO Gaming Galaxy LOGO</Link>
          </div>
          <div>
            {user ? (
              <>
                <div>{user.username}</div>
                <LogoutButton />
              </>
            ) : (
              <>
                <Link href="/register">register</Link>
                <Link href="/login">login</Link>
              </>
            )}
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
